// Static checks for the single-file app, without extra dependencies:
//  - the inline script and the Web Worker source compile,
//  - element ids are unique,
//  - every $('#id') lookup in the script points at an id that exists in the page (or is created at runtime).
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import vm from 'node:vm';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const html = readFileSync(path.join(root, 'CDQP.Offline.Audio.Master.html'), 'utf8');
const problems = [];

const scripts = [...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(m => m[1]);
if (scripts.length !== 1) problems.push(`expected one inline <script>, found ${scripts.length}`);
const js = scripts.join('\n');
try { new vm.Script(js, { filename: 'app.js' }); } catch (e) { problems.push(`app script: ${e.message}`); }

const worker = js.match(/function workerScript\(\)\{return `([\s\S]*?)`\}/);
if (!worker) problems.push('worker source not found');
else try { new vm.Script(worker[1], { filename: 'worker.js' }); } catch (e) { problems.push(`worker script: ${e.message}`); }

const markup = html.replace(/<script>[\s\S]*?<\/script>/g, '');
const ids = [...markup.matchAll(/\sid="([^"]+)"/g)].map(m => m[1]);
const seen = new Set();
for (const id of ids) { if (seen.has(id)) problems.push(`duplicate id="${id}"`); seen.add(id); }

// ids generated by the script itself (templates / createElement)
for (const m of js.matchAll(/id="([A-Za-z][\w-]*)\$\{[^}]+\}"/g)) seen.add(`${m[1]}*`);
for (const m of js.matchAll(/id="([A-Za-z][\w-]*)"/g)) seen.add(m[1]);
const known = id => seen.has(id) || [...seen].some(s => s.endsWith('*') && id.startsWith(s.slice(0, -1)));
const lookups = new Set([...js.matchAll(/\$\('#([A-Za-z][\w-]*)'\)/g)].map(m => m[1]));
for (const id of lookups) if (!known(id)) problems.push(`$('#${id}') has no matching element`);

if (problems.length) {
  console.log(problems.map(p => `  ✗ ${p}`).join('\n'));
  process.exit(1);
}
console.log(`  ✓ scripts compile, ${ids.length} ids unique, ${lookups.size} element lookups resolved`);
